### ISSUE TITLE
Modifying error so re-thrown shows original stacktrace

### ISSUE THREAD

**Issue by sheerun** [gajus/get-stack-trace#1]
My goal is to catch error and modify it so re-thrown shows correct stacktrace, is it possible with this library? Something like:

```
try {
  // code
} catch (err) {
  throw getOriginalError(err)
}
```

**Comment by gajus** [comment]
Whats the purpose of re-throwing the error?

Handle the error at the top level and use `getOriginalStackTrace` to resolve the stack trace.

**Comment by gajus** [comment]
Use [`uncaughtException`](https://nodejs.org/api/process.html#process_event_uncaughtexception).

**Comment by sheerun** [comment]
I'm talking about the case when uncaughtException already exists or error reporting is already in place.
