### ISSUE TITLE
Compatibility with Node.js' built in source-map support

### ISSUE THREAD

**Issue by bcoe** [gajus/get-stack-trace#3]
_Hey @gajus came across this repo reading your comments on [stack-trace](https://www.npmjs.com/package/stack-trace)_.

We've recently been building out an experimental API for source-maps in [Node.js itself](https://github.com/nodejs/node/commit/521b2224c3b06de811f3d8353cce5e4a69239864). It's my goal to find some of the foundational libraries in the community that use `prepareStackTrace`, with the goal of potentially wiring in Node.js' built in source-map cache.

On my mind is stack-trace, [express](https://github.com/dougwilson/nodejs-depd/issues/39), winston, and bunyan.

Have any thoughts regarding a good approach ... I'm thinking if we could get some of your work in `get-stack-trace` upstreamed to `stack-trace`, it would help us support Winston.

Given your knowledge in the space, I'd also love your thoughts on how we'd add support to express (which overrides `prepareStackTrace` in `depd`), without stepping on the toes of bunyan/winston.

**Comment by bcoe** [comment]
@dougwilson I've been doing some research into how we could better support stack-traces in express without stepping on the toes of libraries like Winston, turns out the module `stack-trace` might be a good starting point.

**Comment by gajus** [comment]
> Have any thoughts regarding a good approach ... I'm thinking if we could get some of your work in get-stack-trace upstreamed to stack-trace, it would help us support Winston.

Of course.
